module.exports = {
  envVars: {
    SG_PRIVATE_KEY_VAR: "SG_DMQ_CE_PRIVATE_KEY",
    SG_TWITTER_AUTH_KEY_VAR: "SG_DMQ_CE_TWITTER_AUTH_KEY",
    SG_TRIGGER_CACHE_API_VAR: "SG_DMQ_CE_TRIGGER_CACHE_API_VALUE",
  },
};
